name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: cargo install --path .
      - name: Build
        run: chmod +x ./scripts/build.sh && ./scripts/build.sh
      - name: Run tests
        run: ls -l target
